---
test/unit:
  - "**/*_test.go"

test/integration:
  - tests/*
  - tests/*/**

kind/yaml:
  - "**/*.yaml"

kind/pkg:
  - pkg/**/*

terraform/provider:
  - "pkg/terrable/provider*"

terraform/hcl:
  - "**/*.tf"
