---
name: Docker Image CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make build-docker
    - name: Run integration tests
      run: make test-integration
